module.exports = {
  extends: ['@commitlint/config-conventional'],
  rules: {
    'type-enum': [
      2,
      'always',
      [
        'build',
        'ci',
        'chore',
        'revert',
        'feat',
        'fix',
        'improvement',
        'docs',
        'style',
        'refactor',
        'perf',
        'test',
      ],
    ],
    'scope-enum': [
      2,
      'always',
      [
        'logger',
        'service',
        'module',
        'interceptor',
        'deps',
        'docs',
        'release',
        'socket.io',
        'fastify',
        'ws',
        'tcp',
        'kafka',
        'gql',
        'gql-fastify',
        'grpc',
        'mqtt',
        'nats',
        'rmq',
        'redis',
      ],
    ],
  },
};
