import { Reflector } from '@nestjs/core';

import { MODULE_OPTIONS_TOKEN } from './ogma-core.module-definition';

export const OGMA_INSTANCE = 'OGMA_INSTANCE';
export const OGMA_CONTEXT = 'OGMA_CONTEXT';
export const OGMA_OPTIONS = MODULE_OPTIONS_TOKEN;
export const MESSAGE_METADATA = 'message';
export const MICROSERVICE_METADATA = 'microservices:pattern';
export const OGMA_INTERCEPTOR_OPTIONS = 'OGMA_INTERCEPTOR_OPTIONS';
export const OGMA_SERVICE_OPTIONS = 'OGMA_SERVICE_OPTIONS';
export const OGMA_INTERCEPTOR_SKIP = 'OGMA_INTERCEPTOR_SKIP';
export const OGMA_SERVICE_TOKEN = 'OGMA_SERVICE';
export const OGMA_REQUEST_SCOPED_SERVICE_TOKEN = 'OGMA_REQUEST_SCOPED_SERVICE';
export const OGMA_INTERCEPTOR_PROVIDERS = [OGMA_INTERCEPTOR_OPTIONS, Reflector];
export const OGMA_TRACE_METHOD_OPTION = 'OGMA_TRACE_METHOD_OPTION';
export const OGMA_CONTEXT_PARSER = 'OGMA_CONTEXT_PARSER';
