export const OGMA_INSTANCE = Symbol('OGMA_INSTANCE');
export const OGMA_CONTEXT = Symbol('OGMA_CONTEXT');
export const OGMA_OPTIONS = Symbol('OGMA_OPTIONS');
export const OGMA_INTERCEPTOR_OPTIONS = Symbol('OGMA_INTERCEPTOR_OPTIONS');
export const OGMA_SERVICE_OPTIONS = Symbol('OGMA_SERVICE_OPTIONS');
export const OGMA_INTERCEPTOR_SKIP = Symbol('OGMA_INTERCEPTOR_SKIP');
