export const OGMA_INSTANCE = 'OGMA_INSTANCE';
export const OGMA_CONTEXT = 'OGMA_CONTEXT';
export const OGMA_OPTIONS = 'OGMA_OPTIONS';
export const MESSAGE_METADATA = 'message';
export const MICROSERVICE_METADATA = 'microservices:pattern';
export const OGMA_INTERCEPTOR_OPTIONS = 'OGMA_INTERCEPTOR_OPTIONS';
export const OGMA_SERVICE_OPTIONS = 'OGMA_SERVICE_OPTIONS';
export const OGMA_INTERCEPTOR_SKIP = 'OGMA_INTERCEPTOR_SKIP';
