name: 'Run Build, Lint, Format Check, Tests, and Coverage Collection'
description: 'Run the required actions'
runs:
  using: 'composite'
  steps:
    - name: Start Docker Compose
      run: docker-compose up -d
      shell: bash
    - name: Install pnpm
      run: npm i -g pnpm
      shell: bash
    - name: Install deps
      run: pnpm i --frozen-lockfile=false
      shell: bash
    - name: Build Project
      run: pnpm build
      shell: bash
    - name: Run Linter
      run: pnpm lint
      shell: bash
    - name: Run Unit Tests
      run: pnpm test
      shell: bash
    - name: Run Integration Tests
      run: pnpm test:int
      shell: bash
      env:
        NX_CLOUD_DISTRIBUTED_EXECUTION: false
    - name: Stop Nx Cloud Agents
      run: pnpx -y nx-cloud stop-all-agents
      shell: bash
    - name: Stop Docker Compose
      run: docker-compose down
      shell: bash
    - name: Merge Coverages
      run: pnpm coverage -- --skip-nx-cache
      shell: bash
      env:
        NX_CLOUD_DISTRIBUTED_EXECUTION: false
    - name: Debug Coverage
      run: cat coverage/lcov.info
      shell: bash
    - name: Upload Coverage
      uses: actions/upload-artifact@master
      with:
        name: coverage
        path: coverage/lcov.info