name: 'Run Build, Lint, Format Check, Tests, and Coverage Collection'
description: 'Run the required actions'
runs:
  using: 'composite'
  steps:
    - name: Start Docker Compose
      run: docker-compose up -d
    - name: Install pnpm
      run: npm i -g pnpm
    - name: Install deps
      run: pnpm i --frozen-lockfile=false
    - name: Build Project
      run: pnpm build
    - name: Run Linter
      run: pnpm lint
    - name: Run Unit Tests
      run: pnpm test:cov
    - name: Run Integration Tests
      run: pnpm test:int
      env:
        NX_CLOUD_DISTRIBUTED_EXECUTION: false
    - name: Stop Nx Cloud Agents
      run: pnpx -y nx-cloud stop-all-agents
    - name: Stop Docker Compose
      run: docker-compose down
    - name: Merge Coverages
      run: pnpm coverage
      env:
        NX_CLOUD_DISTRIBUTED_EXECUTION: false
    - name: Debug Coverage
      run: cat coverage/lcov.info
    - name: Send Coverage
      if:  ${{ !contains(github.event.pull_request.user.login, 'dependabot') }}
      run: pnpm sendCoverage
      env:
        CODECLIMATE_API_HOST: https://codebeat.co/webhooks/code_coverage
        CODECLIMATE_REPO_TOKEN: ${{ secrets.CODECLIMATE_REPO_TOKEN }}