name: Documentation Deployment

on:
  push:
    branches:
      - 'main'
  workflow-dispatch:

# Allow this job to clone the repo and create a page deployment
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  docs-changed:
    runs-on: ubuntu-latest
    outputs:
      files: ${{ contains(steps.files.outputs.added_modified, 'apps/docs/') }}
    steps:
      - name: Get All Added and Modified Field
        id: files
        uses: jitterbit/get-changed-files@v1
      - name: Echo contains
        run: echo ${{ contains(steps.files.outputs.added_modified, 'apps/docs/')  }}

  build-docs:
    runs-on: ubuntu-latest
    needs:
      - docs-changed
    if: ${{ needs.docs-changed.outputs.files == 'true' }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: Install pnpm
        run: npm i -g pnpm
      - name: Dependencies Install
        run: pnpm i
      - name: Build Docs
        run: pnpm nx build docs
      - name: Upload build
        uses: actions/upload-artifact@v3
        with:
          name: github-pages
          path: dist/apps/docs/
          if-no-files-found: error

  docs-deploy:
    runs-on: ubuntu-latest
    needs:
      - build-docs
    permissoins:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: GitHub Pages Deploy Step
        uses: actions/deploy-pages@v1
        id: deployment
